### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by asadmehdi785** [stephlaf/colmaracademy#1]
Nice job using HTML5 tags such as `header`, `nav`, and `footer`, to make your markup more semantic! To improve on this further, you can also make use of other HTML5 tags such as `main`, `section`, and `figure` to increase the semantic meaning of your code. This will make your HTML easier to read through and reason about, as well as reducing the reliance on `div` tags.

**Comment by stephlaf** [comment]
Sweet, thanks.
