### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by asadmehdi785** [stephlaf/colmaracademy#5]
Outstanding work on this project! Your HTML and CSS code was well structured and readable, and I especially liked the usage of comments to separate the code for different parts of the webpage. In addition, the project itself was structured in an organized way, with stylesheets, images, and videos being put in their own respective location. This kind of separation of concerns was very good to see, so good job with that!

With regards to the specification, you followed it very closely, while adding some of your own customizations. In addition, the responsiveness of the webpage was done very well. Excellent work!

I hope you enjoyed the course!

Grade: Exceeds expectations

**Comment by stephlaf** [comment]
Wow, thanks! I did enjoy!

**Comment by asadmehdi785** [comment]
You're welcome! Glad you enjoyed it.
